COMPANIES = [
    # --- Adani Group ---
    {"symbol": "ACC.NS", "name": "ACC Ltd"},
    {"symbol": "ADANIENT.NS", "name": "Adani Enterprises Ltd"},
    {"symbol": "ADANIGREEN.NS", "name": "Adani Green Energy Ltd"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports & SEZ Ltd"},
    {"symbol": "ADANIENSOL.NS", "name": "Adani Energy Solutions Ltd"},
    {"symbol": "ATGL.NS", "name": "Adani Total Gas Ltd"},
    {"symbol": "AMBUJACEM.NS", "name": "Ambuja Cements Ltd"},
    
    # --- Banking & Finance ---
    {"symbol": "AXISBANK.NS", "name": "Axis Bank Ltd"},
    {"symbol": "BANDHANBNK.NS", "name": "Bandhan Bank Ltd"},
    {"symbol": "BANKBARODA.NS", "name": "Bank of Baroda"},
    {"symbol": "BANKINDIA.NS", "name": "Bank of India"},
    {"symbol": "CANBK.NS", "name": "Canara Bank"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank Ltd"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank Ltd"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank Ltd"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank Ltd"},
    {"symbol": "PNB.NS", "name": "Punjab National Bank"},
    {"symbol": "SBIN.NS", "name": "State Bank of India"},
    {"symbol": "UNIONBANK.NS", "name": "Union Bank of India"},
    {"symbol": "FEDERALBNK.NS", "name": "Federal Bank Ltd"},
    {"symbol": "IDFCFIRSTB.NS", "name": "IDFC First Bank Ltd"},
    {"symbol": "AUBANK.NS", "name": "AU Small Finance Bank Ltd"},
    
    # --- Auto ---
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto Ltd"},
    {"symbol": "EICHERMOT.NS", "name": "Eicher Motors Ltd"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp Ltd"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki India Ltd"},
    {"symbol": "TVSMOTOR.NS", "name": "TVS Motor Company Ltd"},
    {"symbol": "SONACOMS.NS", "name": "Sona BLW Precision Forgings Ltd"},
    {"symbol": "MOTHERSON.NS", "name": "Samvardhana Motherson Intl Ltd"}, # Replaced defunct/older tickers
    
    # --- Handling Special Characters (BE CAREFUL) ---
    {"symbol": "M&M.NS", "name": "Mahindra & Mahindra Ltd"},
    {"symbol": "ARE&M.NS", "name": "Amara Raja Energy & Mobility Ltd"}, 
    
    # --- IT & Tech ---
    {"symbol": "HCLTECH.NS", "name": "HCL Technologies Ltd"},
    {"symbol": "INFY.NS", "name": "Infosys Ltd"},
    {"symbol": "LTIM.NS", "name": "LTIMindtree Ltd"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services Ltd"},
    {"symbol": "TECHM.NS", "name": "Tech Mahindra Ltd"},
    {"symbol": "WIPRO.NS", "name": "Wipro Ltd"},
    {"symbol": "COFORGE.NS", "name": "Coforge Ltd"},
    {"symbol": "KPITTECH.NS", "name": "KPIT Technologies Ltd"},
    {"symbol": "LTTS.NS", "name": "L&T Technology Services Ltd"},
    {"symbol": "MPHASIS.NS", "name": "Mphasis Ltd"},
    {"symbol": "PERSISTENT.NS", "name": "Persistent Systems Ltd"},
    
    # --- Pharma & Healthcare ---
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals Enterprise Ltd"},
    {"symbol": "BIOCON.NS", "name": "Biocon Ltd"},
    {"symbol": "CIPLA.NS", "name": "Cipla Ltd"},
    {"symbol": "DIVISLAB.NS", "name": "Divi's Laboratories Ltd"},
    {"symbol": "DRREDDY.NS", "name": "Dr. Reddy's Labs Ltd"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharma Ltd"},
    {"symbol": "LUPIN.NS", "name": "Lupin Ltd"},
    {"symbol": "AUROPHARMA.NS", "name": "Aurobindo Pharma Ltd"},
    {"symbol": "TORNTPHARM.NS", "name": "Torrent Pharmaceuticals Ltd"},
    {"symbol": "ALKEM.NS", "name": "Alkem Laboratories Ltd"},
    {"symbol": "GLENMARK.NS", "name": "Glenmark Pharmaceuticals Ltd"},
    {"symbol": "ZYDUSLIFE.NS", "name": "Zydus Lifesciences Ltd"},
    
    # --- Others (Energy, FMCG, etc) ---
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints Ltd"},
    {"symbol": "BPCL.NS", "name": "Bharat Petroleum Corp Ltd"},
    {"symbol": "BRITANNIA.NS", "name": "Britannia Industries Ltd"},
    {"symbol": "COALINDIA.NS", "name": "Coal India Ltd"},
    {"symbol": "DABUR.NS", "name": "Dabur India Ltd"},
    {"symbol": "GRASIM.NS", "name": "Grasim Industries Ltd"},
    {"symbol": "GODREJCP.NS", "name": "Godrej Consumer Products Ltd"},
    {"symbol": "HINDALCO.NS", "name": "Hindalco Industries Ltd"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever Ltd"},
    {"symbol": "IOC.NS", "name": "Indian Oil Corp Ltd"},
    {"symbol": "ITC.NS", "name": "ITC Ltd"},
    {"symbol": "JSWSTEEL.NS", "name": "JSW Steel Ltd"},
    {"symbol": "LT.NS", "name": "Larsen & Toubro Ltd"},
    {"symbol": "NESTLEIND.NS", "name": "Nestlé India Ltd"},
    {"symbol": "NTPC.NS", "name": "NTPC Ltd"},
    {"symbol": "ONGC.NS", "name": "Oil & Natural Gas Corp Ltd"},
    {"symbol": "POWERGRID.NS", "name": "Power Grid Corp of India Ltd"},
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries Ltd"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer Products Ltd"},
    {"symbol": "TATASTEEL.NS", "name": "Tata Steel Ltd"},
    {"symbol": "TITAN.NS", "name": "Titan Company Ltd"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement Ltd"},
    {"symbol": "UPL.NS", "name": "UPL Ltd"},
    {"symbol": "VEDL.NS", "name": "Vedanta Ltd"},
    {"symbol": "PIDILITIND.NS", "name": "Pidilite Industries Ltd"},
    {"symbol": "SHREECEM.NS", "name": "Shree Cement Ltd"},
    {"symbol": "HAVELLS.NS", "name": "Havells India Ltd"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel Ltd"},
]